#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'appointment_app') THEN
    CREATE ROLE appointment_app WITH LOGIN PASSWORD '${APPOINTMENT_DB_APP_PASSWORD}';
  ELSE
    ALTER ROLE appointment_app WITH PASSWORD '${APPOINTMENT_DB_APP_PASSWORD}';
  END IF;
END
\$\$;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO appointment_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO appointment_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO appointment_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO appointment_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO appointment_app;
EOSQL
